wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
format_strings = true
hex_literal_case = "Upper"
imports_granularity = "Module"
group_imports = "StdExternalCrate"
reorder_impl_items = true
combine_control_expr = false
overflow_delimited_expr = true
force_multiline_blocks = true
edition = "2021"
use_field_init_shorthand = true